######################################################################
# Automatically generated by qmake (3.1) Thu Oct 26 10:40:56 2017
######################################################################
QT += core widgets
TEMPLATE = app
TARGET = HelloQT
INCLUDEPATH += .

# Input
SOURCES += main.cpp
